<?php

return [
    'weight' => [
        'gr' => ['name' => 'Gram', 'abbr' => 'gr'],
        'gros' => ['name' => 'Gross', 'abbr' => 'gros'],
        'kg' => ['name' => 'Kilogram', 'abbr' => 'kg'],
        'mg' => ['name' => 'Miligram', 'abbr' => 'mg'],
        'oz' => ['name' => 'Ons', 'abbr' => 'oz'],
        'ton' => ['name' => 'Ton', 'abbr' => 'ton'],
    ],
    'volume' => [
        'l' => ['name' => 'Liter', 'abbr' => 'l'],
        'ml' => ['name' => 'Mililiter', 'abbr' => 'ml'],
        'm3' => ['name' => 'Meter Kubik', 'abbr' => 'm³'],
    ],
    'length' => [
        'cm' => ['name' => 'Centimeter', 'abbr' => 'cm'],
        'm' => ['name' => 'Meter', 'abbr' => 'm'],
        'mm' => ['name' => 'Milimeter', 'abbr' => 'mm'],
    ],
    'packaging' => [
        'bal' => ['name' => 'Bal', 'abbr' => 'bal'],
        'btg' => ['name' => 'Batang', 'abbr' => 'btg'],
        'btl' => ['name' => 'Botol', 'abbr' => 'btl'],
        'bks' => ['name' => 'Bungkus', 'abbr' => 'bks'],
        'box' => ['name' => 'Box', 'abbr' => 'box'],
        'btr' => ['name' => 'Butir', 'abbr' => 'btr'],
        'dozen' => ['name' => 'Dozen', 'abbr' => 'dzn'],
        'drum' => ['name' => 'Drum', 'abbr' => 'drm'],
        'dus' => ['name' => 'Dus', 'abbr' => 'dus'],
        'galon' => ['name' => 'Galon', 'abbr' => 'gal'],
        'ikat' => ['name' => 'Ikat', 'abbr' => 'ikat'],
        'kaleng' => ['name' => 'Kaleng', 'abbr' => 'klg'],
        'karton' => ['name' => 'Karton', 'abbr' => 'ktn'],
        'karung' => ['name' => 'Karung', 'abbr' => 'krg'],
        'kodi' => ['name' => 'Kodi', 'abbr' => 'kodi'],
        'kontainer' => ['name' => 'Kontainer', 'abbr' => 'cnt'],
        'kuintal' => ['name' => 'Kuintal', 'abbr' => 'kwint'],
        'krat' => ['name' => 'Krat', 'abbr' => 'krat'],
        'orange' => ['name' => 'Orang', 'abbr' => 'org'],
        'pack' => ['name' => 'Pack', 'abbr' => 'pack'],
        'pallet' => ['name' => 'Pallet', 'abbr' => 'pallet'],
        'pcs' => ['name' => 'Pieces', 'abbr' => 'pcs'],
        'resep' => ['name' => 'Resep', 'abbr' => 'res'],
        'rim' => ['name' => 'Rim', 'abbr' => 'rim'],
        'rol' => ['name' => 'Rol', 'abbr' => 'rol'],
        'sachet' => ['name' => 'Sachet', 'abbr' => 'sachet'],
        'set' => ['name' => 'Set', 'abbr' => 'set'],
        'sheet' => ['name' => 'Sheet', 'abbr' => 'sh'],
        'slop' => ['name' => 'Slop', 'abbr' => 'slop'],
        'strip' => ['name' => 'Strip', 'abbr' => 'strip'],
        'tim' => ['name' => 'Tim', 'abbr' => 'tim'],
        'unit' => ['name' => 'Unit', 'abbr' => 'unit'],
    ]
];